# -*- coding: utf-8 -*-
"""covid-19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t87I7WpL5S3iRdjEeq7SQls1tp1nZZgI
"""

import numpy as np
import pandas as pd

path = "/content/drive/MyDrive/CSE BUET/Level-4, Term-2/CSE 400/COVID-19/US-Data-Edited/"

from scipy import stats

def spearmanr(a, b):
  cut = a.astype(bool).argmax()
  if a[cut] == 0:
    return np.nan, np.nan
  else:
    return stats.spearmanr(a[cut:], b[cut:])

ts_df = pd.read_csv(path+'time_series-county_all.csv')

df = ts_df.pivot(index="countyFIPS", columns="Date", values=["Mean T",	"Min T",	"Max T",	"Total Precipitation",	"Relative Humidity",	"COVID Confirmed",	"COVID Deaths"])

sp = np.vectorize(spearmanr, signature='(n),(n)->(),()')

cor, p_val = sp([[df["COVID Confirmed"]], [df["COVID Deaths"]]], [df["Mean T"],	df["Min T"],	df["Max T"],	df["Total Precipitation"],	df["Relative Humidity"]])

index = df.index
columns = pd.MultiIndex.from_product([["Mean T",	"Min T",	"Max T",	"Total Precipitation",	"Relative Humidity"], ['correlation', 'pvalue']],
                                     names=['subject', 'spearman'])

files = [path+"spearman-county_covid_confirmed.csv", path+"spearman-county_covid_deaths.csv"]
for i in range(2):
  data = np.dstack((cor[i].T,p_val[i].T)).ravel().reshape((3141,-1))
  df = pd.DataFrame(data0, index=index, columns=columns)
  df.to_csv(files[i])